### PR TITLE
Qingwei/rx

### PR DESCRIPTION
**Pull request by qingweibinary**
Ignore the branch name

### CODE REVIEW

**Comment by qingweibinary** [comment]
@borisyankov 

I just realize an issue, let's discuss

This PR handle unsubscribe in ApiState, so when reconnect, we do not subscribe to stream that had been forgotten.

Then I discover next-gen is works by hooking on `authorize`, and do all those subscription again.

This raise a question, should we do all those resubscription for caller, or maybe we only reauthorize, and let them handle themselves?

Or we provide yet another switch to opt-in ?

@aminmarashi maybe you can provide some insight too

**Comment by aminmarashi** [comment]
@borisyankov @qingweibinary In my opinion it's best that all resubscriptions are handled for caller, because it's the most common usage.

**Comment by borisyankov** [comment]
Yeah, I also think so.

**Comment by qingweibinary** [comment]
codacy complains about console.warn, let's ignore codacy =P

the warning is for deprecation, maybe next 2 release we can remove that 2 calls

**Pull request merged**
